### ISSUE TITLE
Error undefined: sha256.Sum256

### ISSUE THREAD

**Issue by jniltinho** [martini-contrib/auth#10]
go get github.com/martini-contrib/auth
# github.com/martini-contrib/auth
src/github.com/martini-contrib/auth/util.go:10: undefined: sha256.Sum256
src/github.com/martini-contrib/auth/util.go:11: undefined: sha256.Sum256

Ubuntu 13.10 64Bits
Golang 1.2

**Comment by attilaolah** [comment]
Trusty is [still stuck with 1.2](http://packages.ubuntu.com/trusty/golang), however that should be sufficient. Please reopen if this is still an issue.
